
owner: goeckslab
categories:
  - Machine Learning
remote_repository_url: https://github.com/goeckslab/Galaxy-Ludwig.git
homepage_url: https://ludwig-ai.github.io/ludwig-docs
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for ludwig tool: {{ tool_name }}"
suite:
  name: suite_ludwig
  description: Ludwig is a declarative deep learning framework that allows users to train, evaluate, and deploy models.
