FROM ludwigai/ludwig-ray-gpu

RUN pip install -U pip

RUN pip install --no-cache-dir 'git+https://github.com/goeckslab/model-unpickler.git' && \
    pip install --no-cache-dir 'git+https://github.com/goeckslab/smart-report.git@17df590f3ceb065add099f37b4874c85bd275014'
