input_features:
- name: ''
  encoder:
    type: passthrough
  type: number
output_features:
- name: ''
  decoder:
    num_fc_layers: 0
    output_size: 256
    fc_dropout: 0.0
    type: classifier
  loss:
    type: softmax_cross_entropy
  top_k: 3
  type: category
combiner:
  type: concat
trainer:
  batch_size: 128
  epochs: 100
  optimizer:
    type: adam
  learning_rate: 0.001
  early_stop: 5
model_type: ecd
